### ISSUE TITLE
Feature Request: recognize es6 code in html files

### ISSUE THREAD

**Issue by webstermath** [JeanRemiDelteil/appsScriptColor#1]
It would be great if Apps Script Color could recognize and properly color es6 code in html files.  Thank you.

**Comment by JeanRemiDelteil** [comment]
Currently the Code colorization is not performed by AppsScriptColor, but by the script.google.com UI itself.

AppsScriptColor only allows to change the color applied. Until the GAS editor updates its outdated version of the code editor, it is unlikely to be possible.
