### ISSUE TITLE
Porting the extension to Firefox

### ISSUE THREAD

**Issue by TasseDeCafe** [JeanRemiDelteil/appsScriptColor#10]
Hi Jean!

Is there any chance we could have a Firefox version of the extension?

I might even be able to start working on it myself, it seems to be relatively easy to do the conversion, but I have no experience with that.

**Comment by JeanRemiDelteil** [comment]
it could be nice to have it on Firefox.
The extension format should be quite similar

**Comment by JeanRemiDelteil** [comment]
I do not have the time for this. If someone want to take on that project, please contact me.
