### ISSUE TITLE
Conflicts with GAS GitHub Assistant

### ISSUE THREAD

**Issue by wbvtler** [JeanRemiDelteil/appsScriptColor#2]
I am unable to have both this extension and GAS GitHub Assistant at the same time, which is a huge bummer because I love them both. I have attached the GHA ticket url below, hopefully something can be worked out.

https://github.com/leonhartX/gas-github/issues/67

**Comment by leonhartX** [comment]
@JeanRemiDelteil seems your extension will add a CR/LF to filename,  could you please take a look at that?
@wbvtler FYI I'll make a change in gas-github to fix this.

**Comment by JeanRemiDelteil** [comment]
https://github.com/leonhartX/gas-github/pull/70 should fix this.

Filename are not edited, only the HTML displaying the list.

Get the FULL file name from the attribute "title" of **div.gwt-Label.piece.name** inside **div.project-items-list**
This attribute is correctly update by the GAS editor UI, while the aria-label is not, and the text content will be updated to remove the folder-like part of the file name by AppsScriptColor.
