### ISSUE TITLE
Creating a New Project (script) with the Extension will crash Chrome

### ISSUE THREAD

**Issue by JeanRemiDelteil** [JeanRemiDelteil/appsScriptColor#22]
From the "My project" page (https://script.google.com/home), clicking "New Project" will crash Chrome.

**Comment by Nu11u5** [comment]
Is this project still maintained?  This bug still exists.  It also affects creating a new script embedded in a Google doc/sheet container through the document editor page.  Chrome does not "crash" but the page fails to fully load.  The script project will open fine when finding it on the Apps Script home page.
