### ISSUE TITLE
Fails to Recognize JS inside <script type="module"> Tag

### ISSUE THREAD

**Issue by webstermath** [JeanRemiDelteil/appsScriptColor#37]
If a script tag in am HTML file contains a type attribute, AppsScript Color does not recognize the contained javascript and color it.

**Comment by JeanRemiDelteil** [comment]
@webstermath AppsScriptColor does not color the code, the coloration is done by the AppsScript editor.
AppsScriptColor only define new color theme, and apply them.

This is sadly out-of-scope.
