### ISSUE TITLE
Chrome update -> Extension doesn't work

### ISSUE THREAD

**Issue by Dzabol** [JeanRemiDelteil/appsScriptColor#39]
Hello, 
after latest chrome update 08.03.2023 Extension stop working

**Comment by jdbecht** [comment]
Seeing the following errors in console:
`Error: <path> attribute d: Expected number, "…4853,13.688165 L,17.4142136 L0,0…".`

`injectColor.js:7 This document requires 'TrustedHTML' assignment.`

**Comment by JeanRemiDelteil** [comment]
Thank you for reporting this.
Reproduced with Chrome version 111.0.5563.65

Probably caused by changes in the Browser Extension API.
