### ISSUE TITLE
feature request: multi-line tab selector

### ISSUE THREAD

**Issue by imthenachoman** [JeanRemiDelteil/appsScriptColor#6]
First, I absolutely love this extension. Thank you for writing it. 

It would be nice if we could multi-line the open tabs list. 

I tried to look through the extension source to see if its something I could do myself but I don't have experience with extensions and I'm not sure where in the code to look/start.

**Comment by JeanRemiDelteil** [comment]
Hi @imthenachoman It's nice to know that it's useful to people :)
About your request, i'm not sure to really understand well.

You want the following to be multi-line ?\
![image](https://user-images.githubusercontent.com/9743907/72687271-84a81900-3afc-11ea-9c48-e8036ddad8ea.png)

I'm not sure it would be nice for this to take more vertical space.

First quick CSS investigation shows that it will take a great deal of CSS to tweak this part !

You are welcome to try to come up with a CSS patch.
I can take care of integrating it in the extension behind a setting.

**Comment by imthenachoman** [comment]
Can the extension only modify the CSS or can it inject JS to handle tabs?

I figured out the relevant CSS and got it to show on two lines but it won't work dynamically because the tab bar has a set height in PX and then the code view port is pushed down from the top.

![image](https://user-images.githubusercontent.com/83817/72691369-db105a00-3af2-11ea-8cab-024acb430d10.png)

**Comment by JeanRemiDelteil** [comment]
Oh, okay, you want the tabs themselves to be multi-lined !
I never had this problem where you have so many file open that they disappear to the right of the screen.

I would say that you should not keep a lot of file open, it's a bad and old web editor, so don't overload it.

There are currently a better way to work with AppsScript project with local editing and the CLASP CLI tool, and the typing libraries for AppsScript.
More info on this technique:
- CLASP from Google: https://codelabs.developers.google.com/codelabs/clasp/#0
- My take of the local setup: https://github.com/JeanRemiDelteil/gas-starter-kit
- A project that is using it: https://github.com/JeanRemiDelteil/insert-icons

That said, I found a really simple way to solve the issue with too many tab open:
```css
.editor .gwt-TabLayoutPanelTabs {
    width: auto!important;
    overflow-y: auto;
}
```

And to answer your question about JS / CSS injection, the main code of AppsScript color is JS that is injected in the page.
That JS then add or remove the CSS for the Color themes.
As I want to keep the extension simple and efficient, there are no active monitoring (JS) to manage CSS changes.

**Comment by imthenachoman** [comment]
Yeah, I use clasp but sometimes, for quick changes, prefer the online editor. And I have some complex projects with many files so sometimes I have a lot open. 

I will try that CSS you provided. 

Agreed this is not a high priority or critical feature. I just thought it would be a nice to have for folks who don't/can't use clasp.
